version: '3'

services:
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs/application:/application
    environment:
      - NODE_ENV=development

  nginx:
    container_name: nginx
    build: ./nginx
    hostname: docker-spa-proxy.com
    ports:
    - 80:80
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf